#!/usr/bin/env bash
set -e # halt script on error

#Output in subdirectory because of baseurl
bundle exec jekyll build -d _site/website-test

bundle exec htmlproofer --assume-extension ./website-test
