#!/usr/bin/env bash
set -e # halt script on error

#Output in subdirectory because of baseurl
bundle exec jekyll build -d _site/website-test

bundle exec rake test
#bundle exec htmlproofer --url-ignore "/ianjazz246.github.io\/website-test/"  --assume-extension ./_site
